# Generated by Django 4.1.3 on 2022-12-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autovehicul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('descriere', models.TextField(blank=True, max_length=2000, null=True)),
                ('vizibil', models.BooleanField(default=True)),
                ('vandut', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=100)),
                ('versiune', models.CharField(blank=True, max_length=100, null=True)),
                ('an_fabricatie', models.SmallIntegerField()),
                ('km', models.IntegerField()),
                ('putere', models.SmallIntegerField()),
                ('capacitate_cilindrica', models.SmallIntegerField()),
                ('VIN', models.CharField(blank=True, max_length=50, null=True)),
                ('consum_urban', models.CharField(blank=True, max_length=50, null=True)),
                ('numar_portiere', models.SmallIntegerField()),
                ('culoare', models.CharField(max_length=50)),
                ('optiuni_culoare', models.CharField(max_length=50)),
                ('pret_euro', models.IntegerField()),
                ('garantie', models.CharField(blank=True, max_length=100, null=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('data_modificare', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'autovehicule',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Caroserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'caroserie',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='CategorieDotari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorie dotari',
            },
        ),
        migrations.CreateModel(
            name='Combustibil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'combustibil',
            },
        ),
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('CUI', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('denumire', models.CharField(max_length=50)),
                ('nr_registru_comert', models.CharField(max_length=20)),
                ('adresa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'companie',
            },
        ),
        migrations.CreateModel(
            name='CutieDeViteza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'cutie de viteza',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'marca',
            },
        ),
        migrations.CreateModel(
            name='NormaDePoluare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'norma de poluare',
            },
        ),
        migrations.CreateModel(
            name='Stare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'stare',
            },
        ),
        migrations.CreateModel(
            name='Transmisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'transmisie',
            },
        ),
        migrations.CreateModel(
            name='ImaginiAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(max_length=200, upload_to='auto/images', verbose_name='foto')),
                ('autovehicul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini_auto', to='autoadmin.autovehicul')),
            ],
        ),
        migrations.CreateModel(
            name='Dotare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=100, unique=True)),
                ('categorie_dotari', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.categoriedotari')),
            ],
            options={
                'verbose_name_plural': 'dotari',
            },
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='caroserie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.caroserie'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.categorie'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='combustibil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.combustibil'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='cutie_de_viteza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.cutiedeviteza'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='dotari',
            field=models.ManyToManyField(to='autoadmin.dotare'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.marca'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='norma_de_poluare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.normadepoluare'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='stare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.stare'),
        ),
        migrations.AddField(
            model_name='autovehicul',
            name='transmisie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoadmin.transmisie'),
        ),
    ]
