# Generated by Django 4.1.3 on 2022-12-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autovehicul',
            name='review_post_vanzare',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
