# Generated by Django 4.1.3 on 2022-12-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoadmin', '0002_autovehicul_review_post_vanzare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imaginiauto',
            options={'verbose_name_plural': 'Autovehicule foto bulk upload'},
        ),
        migrations.AlterField(
            model_name='imaginiauto',
            name='autovehicul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagine_auto', to='autoadmin.autovehicul'),
        ),
    ]
