# Generated by Django 4.1.3 on 2022-12-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoadmin', '0003_alter_imaginiauto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutiedeviteza',
            options={'verbose_name_plural': 'cutie de viteze'},
        ),
        migrations.AlterModelOptions(
            name='dotare',
            options={'ordering': ['categorie_dotari', 'denumire'], 'verbose_name_plural': 'dotari'},
        ),
        migrations.AlterModelOptions(
            name='imaginiauto',
            options={'ordering': ['id'], 'verbose_name_plural': 'Autovehicule foto bulk upload'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['denumire'], 'verbose_name_plural': 'marca'},
        ),
    ]
